/* Dados — Emilly Dantas · RSA Dashboard 2026 · FIC Capital Group (1º semestre) */
window.EMILLY_REPORT = {
  CATMAP: {
    administracao: { color: '#4d8fff', label: 'Administração' },
    financeiro:    { color: '#10e8a0', label: 'Financeiro' },
    marketing:     { color: '#9d6fff', label: 'Marketing' },
    juridico:      { color: '#ff8f3f', label: 'Jurídico' },
  },
  KPIS: [
    { ic: '📋', label: 'Total no Portfólio', val: '246', sub: 'Demandas institucionais 2026', color: '#4d8fff' },
    { ic: '✅', label: 'Concluídas', val: '159', sub: '65% do total', color: '#10e8a0' },
    { ic: '⚙️', label: 'Em Execução', val: '43', sub: 'Em andamento', color: '#00d4ff' },
    { ic: '📥', label: 'A Fazer / Revisão', val: '20', sub: 'Na fila', color: '#ffe066' },
    { ic: '⏸️', label: 'Standby', val: '24', sub: 'Pausadas', color: '#9d6fff' },
    { ic: '⏰', label: 'Atrasadas', val: '6', sub: 'Requerem atenção', color: '#ff5a5a' },
    { ic: '🏢', label: 'Empresas do Grupo', val: '17+', sub: 'Matriz documental ativa', color: '#ff8f3f' },
    { ic: '🎓', label: 'Certificações', val: '6', sub: 'CEFIS · FGV · SENAI', color: '#ff5fa0' },
  ],
  MON_L: ['Jan/26', 'Fev/26', 'Mar/26', 'Abr/26', 'Mai/26', 'Jun/26'],
  MON_D: [28, 42, 48, 44, 46, 38],
  CAT_L: ['Concluído', 'Em execução', 'A fazer', 'Standby', 'Atrasadas'],
  CAT_D: [159, 43, 20, 24, 6],
  CAT_C: ['#10e8a0', '#4d8fff', '#ffe066', '#9d6fff', '#ff5a5a'],
  AREA_L: ['Administração', 'Financeiro', 'Marketing', 'Jurídico'],
  AREA_D: [92, 68, 52, 34],
  AREA_COMP: [47, 84, 93, 80],
  PRI_L: ['Emergente', 'Prioridade', 'Urgente'],
  PRI_D: [58, 112, 76],
  TOP_L: ['Conciliação bancária', 'Fluxo de caixa', 'Protocolos / MBP', 'Pareceres jurídicos', 'Diagramação / marketing', 'Contratos sociais', 'Manuais empresas', 'Prospectos'],
  TOP_D: [24, 22, 38, 18, 28, 14, 32, 26],
  SKILLS: [
    { nm: '📊 Gestão de Portfólio', pct: 94, c: '#4d8fff' },
    { nm: '💰 Análise Financeira', pct: 88, c: '#10e8a0' },
    { nm: '📑 Modelagem MBP / DCF', pct: 86, c: '#00d4ff' },
    { nm: '🤝 Integração & Relacionamento', pct: 92, c: '#9d6fff' },
    { nm: '📋 Administração Corporativa', pct: 90, c: '#ff8f3f' },
    { nm: '🎯 Planos de Ação', pct: 85, c: '#ffe066' },
    { nm: '📈 Indicadores & Relatórios', pct: 87, c: '#ff5fa0' },
    { nm: '⚖️ Coordenação Jurídica', pct: 82, c: '#ff5a5a' },
    { nm: '📣 Suporte Marketing', pct: 84, c: '#9d6fff' },
    { nm: '🌐 Financial Modeling (FMVA)', pct: 72, c: '#10e8a0' },
  ],
  TL: [
    { dt: 'Jan/2026', co: 'FIC GROUP', cc: '#4d8fff', ttl: 'Início do semestre — portfólio 2026', desc: 'Consolidação de 246 demandas no RSA Dashboard institucional.' },
    { dt: 'Fev/2026', co: 'FINANCEIRO', cc: '#10e8a0', ttl: 'Conciliações e regimento', desc: 'Conciliação Inter/BB, regimento de associados e contratos sociais (emergente).' },
    { dt: 'Mar/2026', co: 'ADMIN', cc: '#ff8f3f', ttl: 'Pico operacional — protocolos', desc: 'Protocolos comerciais, Giraea, LegalCert, Wall Brazil Infomemo.' },
    { dt: 'Mar/2026', co: 'FINANCEIRO', cc: '#10e8a0', ttl: 'Fluxo de caixa reestruturado', desc: 'Ajuste da planilha Fin e lançamentos do mês corrente.' },
    { dt: 'Abr/2026', co: 'PORTFÓLIO', cc: '#00d4ff', ttl: 'Matriz documental multiempresa', desc: 'Entregas MBP, protocolos adm/fin e DCF em 15+ empresas do grupo.' },
    { dt: 'Mai/2026', co: 'CEFIS / SENAI', cc: '#9d6fff', ttl: 'Certificações concluídas', desc: '6 capacitações — planos de ação, negócios, viabilidade e indicadores.' },
    { dt: 'Jun/2026', co: 'FIC GROUP', cc: '#4d8fff', ttl: 'Relatório semestral', desc: '159 concluídas · 65% · 6 atrasadas — relatório 1º semestre 2026.' },
  ],
  ACH: [
    { icon: 'trophy', ttl: 'Taxa de Conclusão', val: '65%', accent: '#10e8a0', ds: '159 de 246 tarefas finalizadas no semestre' },
    { icon: 'org', ttl: 'Empresas na Matriz', val: '17', accent: '#4d8fff', ds: 'MBP, protocolos, DCF e prospectos no portfólio' },
    { icon: 'metric', ttl: 'Financeiro', val: '84%', accent: '#10e8a0', ds: 'Maior % de conclusão entre as áreas' },
    { icon: 'layers', ttl: 'Marketing', val: '93%', accent: '#9d6fff', ds: 'Conclusão por área — liderança no semestre' },
    { icon: 'alert', ttl: 'Atenção Imediata', val: '6', accent: '#ff5a5a', ds: 'Tarefas atrasadas no portfólio' },
    { icon: 'calendar', ttl: 'Certificações', val: '6', accent: '#00d4ff', ds: 'CEFIS · FGV · SENAI São Paulo' },
  ],
  ANALYSIS: [
    {
      feat: true, wide: false, icon: 'exec', accent: '#4d8fff', ttl: 'Resumo Executivo',
      body: '<p><strong>Emilly Dantas</strong> atua como <strong>Senior Integration Agent</strong> no FIC Capital Group (Jan–Jun/2026). Responsável pelo <strong>RSA Dashboard 2026</strong> com <strong>246 demandas</strong> no portfólio, <strong>159 concluídas (65%)</strong>, coordenação documental multiempresa, rotinas financeiras/administrativas e desenvolvimento de relacionamentos estratégicos.</p>',
    },
    {
      feat: false, wide: false, icon: 'user', accent: '#00d4ff', ttl: 'Perfil Profissional',
      body: '<p>Agente de integração com foco em gestão executiva de tarefas, modelagem documental (MBP, protocolos, DCF, prospectos), conciliações financeiras e interface entre administração, financeiro, marketing e jurídico do grupo.</p>',
    },
    {
      feat: false, wide: false, icon: 'scope', accent: '#9d6fff', ttl: 'Principais Áreas',
      body: '<ul class="an-list"><li>Administração corporativa e protocolos</li><li>Financeiro — fluxo de caixa e conciliação</li><li>Marketing — diagramação e materiais</li><li>Jurídico — pareceres e compliance</li><li>Matriz documental do portfólio</li><li>Prospecção e relacionamento (leads)</li></ul>',
    },
    {
      feat: false, wide: false, icon: 'strength', accent: '#ffe066', ttl: 'Pontos Fortes',
      body: '<ul class="an-list"><li>Visão consolidada de 246 demandas simultâneas</li><li>Alta conclusão em Marketing (93%) e Financeiro (84%)</li><li>Capacitação contínua (6 certificações no semestre)</li><li>Geração de oportunidades via networking</li><li>Padronização documental multiempresa</li></ul>',
    },
    {
      feat: false, wide: false, icon: 'stack', accent: '#10e8a0', ttl: 'Entregas Recorrentes',
      body: '<ul class="an-list"><li>MBP V1/V2 e protocolos administrativos/financeiros</li><li>DCF, REF e prospectos por empresa</li><li>Conciliação bancária Inter e BB</li><li>Fluxo de caixa e despesas correntes</li><li>Pareceres jurídicos e contratos sociais</li><li>Diagramação institucional (Giraea, PCRRB, Wall)</li></ul>',
    },
    {
      feat: true, wide: true, icon: 'impact', accent: '#ff8f3f', ttl: 'Impacto para a Organização',
      body: '<p>Centraliza a <strong>gestão institucional de demandas</strong> do grupo, garantindo rastreabilidade, priorização e entrega documental padronizada em dezenas de empresas. Suporta a transição para <strong>Head of Integration</strong> no 2º semestre com PDI estruturado (FMVA, Conta Azul, redundância operacional).</p>',
    },
  ],
  PORTFOLIO: [
    { emp: 'ANIMA', mbp1: '✔', mbp2: '✔', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: '✔', prosp: 'Em Ex.' },
    { emp: 'BIOFEED', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: 'Em Ex.', prosp: 'Em Ex.' },
    { emp: 'ÇACANA', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: 'Em Ex.', prosp: 'Em Ex.' },
    { emp: 'DEEP CREATORS', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: 'Em Ex.', prosp: 'Em Ex.' },
    { emp: 'FIC CAPITAL', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1', fin: '✔', dcf: '✔', ref: '—', prosp: 'Standby' },
    { emp: 'GOLDEN VALLEY', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: '✔', prosp: 'Em Ex.' },
    { emp: 'WALL BRAZIL', mbp1: '✔', mbp2: '✔', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: 'Em Ex.', prosp: '—' },
    { emp: 'FICCIONÁRIOS', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: 'A Fazer', prosp: 'Standby' },
    { emp: 'IPROTECTOR', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: 'Em Ex.', prosp: 'A Fazer' },
    { emp: 'LEGAL EXPERT', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: 'A Fazer', prosp: 'A Fazer' },
    { emp: 'LEGALCERT', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: '—', prosp: '—' },
    { emp: 'LIV ECO HABITATS', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: 'A Fazer', prosp: 'A Fazer' },
    { emp: 'METAL INVEST PAY', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: 'A Fazer', prosp: 'A Fazer' },
    { emp: 'RWB', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: 'A Fazer', prosp: 'A Fazer' },
    { emp: 'SCAN ATIVOS', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: 'A Fazer', prosp: 'A Fazer' },
    { emp: 'SINATRA', mbp1: '✔', mbp2: 'Em Ex.', prot: 'V1+V2', fin: '✔', dcf: '✔', ref: 'A Fazer', prosp: 'A Fazer' },
    { emp: 'FTS / SUNRISE / TIME 10X', mbp1: 'Standby', mbp2: '—', prot: 'Standby', fin: 'Standby', dcf: '—', ref: '—', prosp: '—' },
  ],
  CERTS: [
    { org: 'CEFIS', title: 'Elaboração e Gestão de Planos de Ação', desc: 'Capacitação voltada à elaboração e execução de planos de ação no contexto organizacional.', skills: ['Gestão Operacional', 'Planejamento Operacional'] },
    { org: 'CEFIS', title: 'Desenvolvimento de Planos de Negócios', desc: 'Estruturação e desenvolvimento de planos de negócios e projetos.', skills: ['Redação de Plano de Negócios', 'Planejamento de Projetos'] },
    { org: 'FGV', title: 'Gestão Financeira Internacional', desc: 'Mercados financeiros globais, gestão de capitais e análise de riscos em operações internacionais.', skills: ['Análise Financeira Internacional', 'Tomada de Decisão Financeira'] },
    { org: 'SENAI', title: 'Estudo de Viabilidade Técnica e Financeira', desc: 'Viabilidade de projetos — aspectos técnicos, recursos e impactos financeiros.', skills: ['Análise de Viabilidade', 'Gestão de Recursos e Custos'] },
    { org: 'SENAI', title: 'Indicadores Financeiros Fundamentais', desc: 'Demonstrativos financeiros e desempenho econômico de empresas.', skills: ['Análise de Indicadores', 'Avaliação de Desempenho'] },
    { org: 'SENAI', title: 'Relatórios Financeiros Elementares', desc: 'Elaboração, organização e interpretação de relatórios financeiros básicos.', skills: ['Organização de Informações Financeiras'] },
  ],
  OPPS: [
    { init: 'EV', name: 'Elton Veras', desc: 'Contato via lista fria — reativado por iniciativa própria. 1ª reunião em 2025 (Marcio, Daniel e Emilly); relacionamento mantido.', tag: 'Lista Fria · Reativação' },
    { init: 'CB', name: 'Cristian Barrios', desc: 'Networking com funcionário LA FINTECH. Análise documental para captação — projeto TSL.', tag: 'Networking · LA FINTECH' },
    { init: 'PM', name: 'Paulo Maia & Juvenil Silva', desc: 'Conexão direta com Paulo Maia → apresentação de Juvenil Silva (imobiliária). Oportunidade estratégica no setor imobiliário.', tag: 'Setor Imobiliário' },
  ],
  PDI: [
    { obj: 'Certificação FMVA', meta: 'Concluir certificação internacional de Financial Modeling & Valuation até dez/2026' },
    { obj: 'Redundância Paulo Robson', meta: 'Mapear, documentar e validar processos estratégicos da liderança' },
    { obj: 'Assumir Demandas Jessica Amorim', meta: 'Dominar rotinas financeiras, fiscais e operacionais' },
    { obj: 'Conta Azul', meta: 'Eliminar Excel para controles financeiros — centralizar na plataforma' },
    { obj: 'Manuais das Empresas', meta: 'Finalizar manual de cada empresa (MBP + Protocolos + DCF + Prospecto)' },
    { obj: 'Apresentação Institucional', meta: 'Apresentar empresas do portfólio com domínio técnico em português e inglês' },
  ],
  TASKS: [
    { name: 'Parecer jurídico > Radar Benefits', cat: 'administracao', area: 'Administração', pri: 'urgente', status: 'concluido', dt: '09/02' },
    { name: 'Descritivos de cargos > ERP', cat: 'administracao', area: 'Administração', pri: 'prioridade', status: 'concluido', dt: '09/02' },
    { name: 'Política de bonificação > Word', cat: 'administracao', area: 'Administração', pri: 'urgente', status: 'concluido', dt: '09/02' },
    { name: 'Conciliação bancária [Inter e BB] > Janeiro 2026', cat: 'financeiro', area: 'Financeiro', pri: 'emergente', status: 'concluido', dt: '11/02' },
    { name: 'Atualização > Regimento de associados', cat: 'administracao', area: 'Administração', pri: 'emergente', status: 'concluido', dt: '11/02' },
    { name: 'Contrato social e CNPJ de todas as empresas', cat: 'administracao', area: 'Administração', pri: 'emergente', status: 'concluido', dt: '16/02' },
    { name: 'Atualização do fluxo de caixa na planilha', cat: 'financeiro', area: 'Financeiro', pri: 'urgente', status: 'concluido', dt: '20/02' },
    { name: 'Giraea > Word', cat: 'administracao', area: 'Administração', pri: 'urgente', status: 'concluido', dt: '25/02' },
    { name: 'Conciliação bancária [Inter e BB] > Fevereiro 2026', cat: 'financeiro', area: 'Financeiro', pri: 'emergente', status: 'concluido', dt: '25/02' },
    { name: 'Atualização das despesas do mês corrente', cat: 'financeiro', area: 'Financeiro', pri: 'emergente', status: 'concluido', dt: '25/02' },
    { name: 'Parecer jurídico > Radar Benefits > Servport', cat: 'administracao', area: 'Administração', pri: 'emergente', status: 'concluido', dt: '25/02' },
    { name: 'Diagramação Giraea e PCRRB', cat: 'marketing', area: 'Marketing', pri: 'urgente', status: 'concluido', dt: '26/02' },
    { name: 'Corrigir catálogo LegalCert — Seção Finanças', cat: 'marketing', area: 'Marketing', pri: 'urgente', status: 'concluido', dt: '27/02' },
    { name: 'Criativo > Vaga em aberto', cat: 'marketing', area: 'Marketing', pri: 'urgente', status: 'concluido', dt: '28/02' },
    { name: 'Proposta > Liv Eco Habitats > Geral', cat: 'marketing', area: 'Marketing', pri: 'emergente', status: 'concluido', dt: '01/03' },
    { name: 'Protocolo comercial', cat: 'marketing', area: 'Marketing', pri: 'urgente', status: 'concluido', dt: '03/03' },
    { name: 'Draft Wall VCP Debt — estrutura visual', cat: 'marketing', area: 'Marketing', pri: 'emergente', status: 'concluido', dt: '07/03' },
    { name: 'PCRRB > Word', cat: 'administracao', area: 'Administração', pri: 'prioridade', status: 'concluido', dt: '08/03' },
    { name: 'FIC Wall Brazil — Infomemo', cat: 'administracao', area: 'Administração', pri: 'prioridade', status: 'concluido', dt: '08/03' },
    { name: 'LegalCert — Novo escopo', cat: 'marketing', area: 'Marketing', pri: 'emergente', status: 'concluido', dt: '08/03' },
    { name: 'RWB — Diagnóstico preliminar', cat: 'administracao', area: 'Administração', pri: 'prioridade', status: 'concluido', dt: '22/03' },
    { name: 'Ajuste estrutura > Fluxo de caixa [planilha Fin]', cat: 'financeiro', area: 'Financeiro', pri: 'emergente', status: 'concluido', dt: '24/03' },
    { name: 'Lançamentos 10/03-18/03 > Despesas mês corrente', cat: 'financeiro', area: 'Financeiro', pri: 'emergente', status: 'concluido', dt: '24/03' },
    { name: 'MBP V2 — ÇACANA', cat: 'administracao', area: 'Administração', pri: 'prioridade', status: 'andamento', dt: '15/04' },
    { name: 'Prospecto — METAL INVEST PAY', cat: 'administracao', area: 'Administração', pri: 'prioridade', status: 'afazer', dt: '30/04' },
    { name: 'REF — SCAN ATIVOS', cat: 'administracao', area: 'Administração', pri: 'prioridade', status: 'afazer', dt: '12/05' },
    { name: 'DCF V1 — SINATRA', cat: 'financeiro', area: 'Financeiro', pri: 'urgente', status: 'andamento', dt: '20/05' },
    { name: 'Protocolo Fin — IPROTECTOR', cat: 'financeiro', area: 'Financeiro', pri: 'emergente', status: 'andamento', dt: '28/05' },
    { name: 'Parecer jurídico — pendência', cat: 'juridico', area: 'Jurídico', pri: 'urgente', status: 'atrasada', dt: '05/02' },
    { name: 'Manual integrado — ANIMA', cat: 'administracao', area: 'Administração', pri: 'prioridade', status: 'standby', dt: '10/06' },
    { name: 'Conta Azul — migração controles', cat: 'financeiro', area: 'Financeiro', pri: 'prioridade', status: 'standby', dt: '30/06' },
    { name: 'Apresentação institucional — GOLDEN VALLEY', cat: 'marketing', area: 'Marketing', pri: 'prioridade', status: 'andamento', dt: '18/06' },
    { name: 'Prospecto — LEGAL EXPERT', cat: 'administracao', area: 'Administração', pri: 'urgente', status: 'afazer', dt: '25/06' },
    { name: 'Treinamento FMVA — módulo 1', cat: 'financeiro', area: 'Financeiro', pri: 'prioridade', status: 'andamento', dt: '01/06' },
    { name: 'Documentação redundância — Paulo Robson', cat: 'administracao', area: 'Administração', pri: 'emergente', status: 'andamento', dt: '15/06' },
    { name: 'Revisão protocolo adm — FICCIONÁRIOS', cat: 'administracao', area: 'Administração', pri: 'prioridade', status: 'standby', dt: '20/06' },
    { name: 'Conciliação bancária — Junho 2026', cat: 'financeiro', area: 'Financeiro', pri: 'emergente', status: 'andamento', dt: '28/06' },
  ],
};
