/* Dados — Gabriel Viana · relatório gabriel.docx (Nov/2025 – Jun/2026) */
window.GABRIEL_REPORT = {
  CATMAP: {
    video:      { color: '#9d6fff', label: 'Vídeo e gravação' },
    material:   { color: '#4d8fff', label: 'Material e conteúdo' },
    identidade: { color: '#ff8f3f', label: 'Identidade visual' },
    pesquisa:   { color: '#10e8a0', label: 'Pesquisa' },
    evento:     { color: '#ff5fa0', label: 'Evento e reunião' },
    roteiro:    { color: '#00d4ff', label: 'Roteiro' },
  },
  KPIS: [
    { ic: '📦', label: 'Entregas Totais', val: '38', sub: 'Legalcert (22) + RWB Agri Invest (16)', color: '#4d8fff' },
    { ic: '🏢', label: 'Empresas', val: '2', sub: 'Legalcert e RWB Agri Invest', color: '#10e8a0' },
    { ic: '🎬', label: 'Vídeos e Gravações', val: '6', sub: 'ADS, reels, workshops e roteiros', color: '#9d6fff' },
    { ic: '📋', label: 'Subdemandas', val: '9', sub: 'Criativos, catálogos e impressos detalhados', color: '#ff8f3f' },
    { ic: '🤝', label: 'Contratos Fechados', val: '3', sub: 'Campanha 13 ADS · tráfego pago', color: '#00d4ff' },
    { ic: '💰', label: 'Receita Rastreável', val: 'R$ 59k', sub: 'Conversões atribuídas à campanha', color: '#ffe066' },
    { ic: '📣', label: 'Campanha 13 ADS', val: '13', sub: 'Início em 07/11/2025 com Fábio', color: '#ff5fa0' },
    { ic: '✔️', label: 'Período', val: '8 meses', sub: 'Nov/2025 a Jun/2026', color: '#10e8a0' },
  ],
  MON_L: ['Nov/25', 'Dez/25', 'Jan/26', 'Fev/26', 'Mar/26', 'Abr/26', 'Mai/26', 'Jun/26'],
  MON_D: [2, 3, 0, 2, 1, 5, 1, 2],
  CAT_L: ['Identidade visual', 'Material e conteúdo', 'Vídeo e gravação', 'Pesquisa', 'Evento e reunião', 'Roteiro'],
  CAT_D: [12, 10, 10, 5, 6, 5],
  CAT_C: ['#ff8f3f', '#4d8fff', '#9d6fff', '#10e8a0', '#ff5fa0', '#00d4ff'],
  CO_L: ['Legalcert', 'RWB Agri Invest'],
  CO_D: [22, 16],
  PILAR_L: ['Posicionamento', 'Pesquisa de mercado', 'Público-alvo'],
  PILAR_D: [28, 5, 5],
  TOP_L: ['Identidade visual', 'Vídeo / gravação', 'Material institucional', 'Workshops e eventos', 'Pesquisa de mercado', 'Roteiros de tráfego', 'Feiras (Agrishow / Agrobrasília)', 'Catálogos e impressos'],
  TOP_D: [12, 10, 10, 6, 5, 5, 4, 8],
  SKILLS: [
    { nm: '🎯 Posicionamento de marca', pct: 95, c: '#4d8fff' },
    { nm: '🎬 Produção audiovisual', pct: 92, c: '#9d6fff' },
    { nm: '📱 Tráfego pago & ADS', pct: 90, c: '#ff5fa0' },
    { nm: '🔍 Pesquisa de mercado', pct: 88, c: '#10e8a0' },
    { nm: '🤝 Público-alvo & parcerias', pct: 86, c: '#00d4ff' },
    { nm: '📐 Identidade visual', pct: 94, c: '#ff8f3f' },
    { nm: '📝 Roteiros e storytelling', pct: 89, c: '#9d6fff' },
    { nm: '🏟️ Eventos e feiras', pct: 87, c: '#ffe066' },
    { nm: '📊 MBP & protocolos', pct: 85, c: '#4d8fff' },
    { nm: '💼 Conversão comercial', pct: 84, c: '#10e8a0' },
  ],
  TL: [
    { dt: 'Nov/2025', co: 'LEGALCERT', cc: '#ff5fa0', ttl: 'Campanha 13 ADS', desc: 'Gravação de 13 anúncios em vídeo com Fábio para tráfego pago — marco da campanha de conversão.' },
    { dt: 'Nov/2025', co: 'LEGALCERT', cc: '#9d6fff', ttl: 'Reels com Emmanuel', desc: 'Conteúdo institucional do porta-voz para redes sociais.' },
    { dt: 'Dez/2025', co: 'LEGALCERT', cc: '#ff5fa0', ttl: 'Workshop Legalcert', desc: 'Workshop presencial, gravação audiovisual e reunião TEC Vidros.' },
    { dt: 'Fev/2026', co: 'LEGALCERT', cc: '#9d6fff', ttl: 'Rota da Seda & tráfego Advisors', desc: 'Gravação de roteiro e roteiros de campanha para Advisors.' },
    { dt: 'Mar/2026', co: 'LEGALCERT', cc: '#ff8f3f', ttl: 'Uniformes Hering', desc: 'Personalização de camisa para uniforme institucional.' },
    { dt: 'Abr/2026', co: 'LEGALCERT', cc: '#9d6fff', ttl: 'Roteiro Templários', desc: 'Criação e gravação com Fábio; workshop presencial.' },
    { dt: 'Abr/2026', co: 'RWB', cc: '#4d8fff', ttl: 'Roteiros Eduardo e Roberto', desc: 'Conteúdo para porta-vozes; crachá Befeed.' },
    { dt: 'Mai/2026', co: 'LEGALCERT', cc: '#ff5fa0', ttl: 'Workshop Legalcert', desc: 'Terceiro workshop presencial no período.' },
    { dt: 'Jun/2026', co: 'RWB', cc: '#ffe066', ttl: 'Agrishow — brindes', desc: 'Bonés e materiais para feira; consolidação de 38 entregas no semestre.' },
  ],
  ACH: [
    { icon: 'trophy', ttl: 'Receita Rastreável', val: 'R$ 59k', accent: '#ffe066', ds: '3 contratos via campanha 13 ADS de tráfego pago' },
    { icon: 'metric', ttl: 'Entregas', val: '38', accent: '#4d8fff', ds: '22 Legalcert + 16 RWB Agri Invest' },
    { icon: 'org', ttl: 'Contratos', val: '3', accent: '#10e8a0', ds: 'Adriano Eduardo, Evandro Digienge e Jean Henriques' },
    { icon: 'layers', ttl: 'Vídeos', val: '6+', accent: '#9d6fff', ds: 'Gravações, ADS, workshops e roteiros em vídeo' },
    { icon: 'alert', ttl: 'Campanha 13 ADS', val: '13', accent: '#ff5fa0', ds: 'Anúncios com Fábio desde 07/11/2025' },
  ],
  CONTRACTS: [
    { client: 'Adriano Eduardo', product: 'Plano Pro', value: 'R$ 3.500,00', origin: 'Tráfego pago — 13 ADS' },
    { client: 'Evandro da Digienge', product: 'Radar Benefits', value: 'R$ 52.000,00', origin: 'Tráfego pago — 13 ADS' },
    { client: 'Jean Henriques', product: 'Contrato Advisor (10x)', value: 'R$ 3.500,00', origin: 'Advisor convertido pelo tráfego pago' },
  ],
  ANALYSIS: [
    {
      feat: true, wide: false, icon: 'exec', accent: '#4d8fff', ttl: 'Resumo Executivo',
      body: '<p><strong>Head de Marketing</strong> no período <strong>Nov/2025 a Jun/2026</strong>, com atuação em <strong>Legalcert</strong> e <strong>RWB Agri Invest</strong>. Registrou <strong>38 entregas</strong> nos pilares de <strong>posicionamento</strong>, <strong>pesquisa de mercado</strong> e <strong>público-alvo</strong>, com <strong>R$ 59.000,00</strong> em receita rastreável a partir da campanha de <strong>13 ADS</strong>.</p>',
    },
    {
      feat: false, wide: false, icon: 'user', accent: '#9d6fff', ttl: 'Perfil e Atribuições',
      body: '<p>Responsável pela estratégia e execução de marketing: identidade visual (hardcopy e softcopy), pesquisas comparadas de concorrentes, análise de público-alvo, parceiros (OAB, CRA, CRECI, ANCORD, SUSEP) e clubes C-Level.</p>',
    },
    {
      feat: false, wide: false, icon: 'scope', accent: '#10e8a0', ttl: 'Pilares de Atuação',
      body: '<ul class="an-list"><li><strong>Posicionamento</strong> — impressos, sites, vídeos, posts, MBP, prospectos</li><li><strong>Pesquisa de mercado</strong> — benchmark e concorrência</li><li><strong>Público-alvo</strong> — leads, workshops, parcerias e feiras</li></ul>',
    },
    {
      feat: false, wide: false, icon: 'strength', accent: '#ffe066', ttl: 'Pontos Fortes',
      body: '<ul class="an-list"><li>Conversão comercial mensurável (R$ 59 mil)</li><li>Produção audiovisual em escala (13 ADS + reels)</li><li>Cobertura de feiras: Agrishow e Agrobrasília</li><li>Entregas contínuas em duas marcas simultâneas</li><li>Protocolo de Marketing 2026 e MBP</li></ul>',
    },
    {
      feat: false, wide: false, icon: 'stack', accent: '#ff8f3f', ttl: 'Principais Entregas',
      body: '<ul class="an-list"><li>Catálogos Advisor e RWB (1ª versão)</li><li>Sites e Google Meu Negócio</li><li>Workshops Legalcert (3 edições)</li><li>Criativos Instagram (SIG, SEE, Agri Partners)</li><li>420+ impressos Agrobrasília · 60 catálogos Agrishow</li></ul>',
    },
    {
      feat: true, wide: true, icon: 'impact', accent: '#ff5fa0', ttl: 'Impacto Comercial',
      body: '<p>A campanha de <strong>tráfego pago com 13 ADS</strong> (início 07/11/2025) gerou <strong>3 contratos fechados</strong>, incluindo o de maior valor (<strong>Radar Benefits — R$ 52.000</strong>). O portfólio de entregas sustenta posicionamento institucional e presença em eventos estratégicos do agronegócio.</p>',
    },
  ],
  TASKS: [
    { name: 'Pesquisa de mercado e análise de concorrência', cat: 'pesquisa', co: 'LEGALCERT', pillar: 'Pesquisa', dt: '—' },
    { name: 'Catálogo Advisor', cat: 'material', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '—' },
    { name: 'Gravação de 13 ADS com Fábio para tráfego pago', cat: 'video', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '07/11' },
    { name: 'Gravação de Reels com Emmanuel', cat: 'video', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '07/11' },
    { name: 'Apresentação comercial Legalcert', cat: 'material', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '—' },
    { name: 'Workshop Legalcert', cat: 'evento', co: 'LEGALCERT', pillar: 'Público-alvo', dt: '11/12' },
    { name: 'Gravação do Workshop', cat: 'video', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '11/12' },
    { name: 'Reunião TEC Vidros', cat: 'evento', co: 'LEGALCERT', pillar: 'Público-alvo', dt: '20/12' },
    { name: 'Protocolo de Marketing 2026 (MBP)', cat: 'material', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '—' },
    { name: 'Assinatura de e-mail para associados', cat: 'identidade', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '—' },
    { name: 'Atualização do Google Meu Negócio', cat: 'identidade', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '—' },
    { name: 'Criativos destaques Instagram (SIG 4 + SEE 4)', cat: 'identidade', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '—' },
    { name: 'Gravação do roteiro Rota da Seda', cat: 'video', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '06/02' },
    { name: 'Roteiros de tráfego para Advisors', cat: 'roteiro', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '23/02' },
    { name: 'Gravação do roteiro de tráfego dos Advisors', cat: 'video', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '23/02' },
    { name: 'Mapeamento de parceiros e eventos estratégicos', cat: 'pesquisa', co: 'LEGALCERT', pillar: 'Público-alvo', dt: '—' },
    { name: 'Personalização de camisa Hering (uniforme)', cat: 'identidade', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '25/03' },
    { name: 'Roteiro Templários com Fábio', cat: 'roteiro', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '04/04' },
    { name: 'Gravação do roteiro Templários', cat: 'video', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '04/04' },
    { name: 'Workshop Legalcert', cat: 'evento', co: 'LEGALCERT', pillar: 'Público-alvo', dt: '15/04' },
    { name: 'Posts para Instagram e LinkedIn', cat: 'material', co: 'LEGALCERT', pillar: 'Posicionamento', dt: '—' },
    { name: 'Workshop Legalcert', cat: 'evento', co: 'LEGALCERT', pillar: 'Público-alvo', dt: '27/05' },
    { name: 'Catálogo RWB Agri Invest (1ª versão)', cat: 'material', co: 'RWB', pillar: 'Posicionamento', dt: '—' },
    { name: 'Atualização da logo RWB', cat: 'identidade', co: 'RWB', pillar: 'Posicionamento', dt: '—' },
    { name: 'Site RWB Agri Invest (1ª versão)', cat: 'material', co: 'RWB', pillar: 'Posicionamento', dt: '—' },
    { name: 'Pesquisa de eventos e feiras do agro', cat: 'pesquisa', co: 'RWB', pillar: 'Pesquisa', dt: '—' },
    { name: 'Benchmark dos principais concorrentes', cat: 'pesquisa', co: 'RWB', pillar: 'Pesquisa', dt: '—' },
    { name: 'Pesquisa de parceiros em potencial', cat: 'pesquisa', co: 'RWB', pillar: 'Público-alvo', dt: '—' },
    { name: 'Criativos Instagram (Agri 6.0, Partners, Captação)', cat: 'identidade', co: 'RWB', pillar: 'Posicionamento', dt: '—' },
    { name: 'Bordado de 12 camisas RWB', cat: 'identidade', co: 'RWB', pillar: 'Posicionamento', dt: '—' },
    { name: 'Compra de 6 camisas Citeral Agro para Fábio', cat: 'identidade', co: 'RWB', pillar: 'Posicionamento', dt: '—' },
    { name: 'Podcast Agroébio com Thiago Moura (Agrishow)', cat: 'evento', co: 'RWB', pillar: 'Posicionamento', dt: '—' },
    { name: 'Impressão de 60 catálogos Agrishow 2026', cat: 'material', co: 'RWB', pillar: 'Posicionamento', dt: '—' },
    { name: 'Confecção de 20 kits de brindes Agrishow', cat: 'identidade', co: 'RWB', pillar: 'Posicionamento', dt: '—' },
    { name: 'Roteiros para Eduardo e Roberto', cat: 'roteiro', co: 'RWB', pillar: 'Posicionamento', dt: '04/04' },
    { name: 'Atualização crachá de viagem Fábio (Befeed)', cat: 'identidade', co: 'RWB', pillar: 'Posicionamento', dt: '14/04' },
    { name: 'Impressos Agrobrasília (120 cat. + 300 folhetos)', cat: 'material', co: 'RWB', pillar: 'Posicionamento', dt: '—' },
    { name: 'Compra de bonés para Agrishow', cat: 'identidade', co: 'RWB', pillar: 'Posicionamento', dt: '13/06' },
  ],
};
