/* Dados do relatório Giovane Oliveira — fonte: giovane.pdf (Jun 2025) + relatorio giovannne.pdf (Jun–Jul 2026) */
window.GIOVANE_REPORT = {
  REPORT_PERIODS: [
    { label: 'Jun 2025', source: 'giovane.pdf', total: 42 },
    { label: 'Jun–Jul 2026', source: 'relatorio giovannne.pdf', total: 37 },
  ],
  CATMAP: {
    helpdesk:     { color: '#4d8fff', label: 'Helpdesk' },
    manutencao:   { color: '#10e8a0', label: 'Manutenção' },
    infra:        { color: '#ff8f3f', label: 'Infraestrutura' },
    apresentacoes:{ color: '#9d6fff', label: 'Apresentações' },
    outros:       { color: '#ffe066', label: 'Outros' },
  },
  KPIS: [
    { ic: '✅', label: 'Total de Tarefas', val: '42', sub: '100% concluídas', color: '#4d8fff' },
    { ic: '🎧', label: 'Helpdesk', val: '28', sub: 'Chamados atendidos', color: '#10e8a0' },
    { ic: '🔧', label: 'Manutenção', val: '7', sub: 'Preventiva + corretiva', color: '#ff8f3f' },
    { ic: '⚡', label: 'Prioridade', val: '41', sub: 'Itens com prioridade', color: '#9d6fff' },
    { ic: '🖥️', label: 'Monitores / TVs', val: '12', sub: 'Equipamento mais atendido', color: '#00d4ff' },
    { ic: '🖨️', label: 'Impressoras', val: '8', sub: 'Atendimentos registrados', color: '#ffe066' },
    { ic: '💻', label: 'Notebooks / PCs', val: '7', sub: 'Suporte e configuração', color: '#ff5fa0' },
    { ic: '✔️', label: 'Conclusão', val: '100%', sub: 'Taxa de tarefas concluídas', color: '#10e8a0' },
    { ic: '📋', label: 'Atividades Jun–Jul/26', val: '37', sub: 'Relatório atualizado · 100% concluídas', color: '#00d4ff' },
    { ic: '⚡', label: 'Prioridade Jun–Jul/26', val: '36', sub: 'Itens marcados como prioridade', color: '#9d6fff' },
    { ic: '🔴', label: 'Urgente Jun–Jul/26', val: '1', sub: 'E-mail licença compartilhada', color: '#ff5a5a' },
  ],
  MON_L: ['Jul/26', 'Jun/26', 'Mai/26', 'Jun/25', 'Mai/25'],
  MON_D: [14, 22, 1, 40, 1],
  CAT_L: ['Helpdesk geral', 'Manutenção', 'Infraestrutura', 'Apresentações', 'Outros'],
  CAT_D: [28, 7, 4, 1, 2],
  CAT_C: ['#4d8fff', '#10e8a0', '#ff8f3f', '#9d6fff', '#ffe066'],
  TOP_L: ['Monitor / TV', 'Impressora', 'Notebook / PC', 'Software / Office', 'Periféricos', 'Office365 / E-mail', 'Helpdesk geral'],
  TOP_D: [12, 8, 7, 5, 4, 6, 5],
  SKILLS: [
    { nm: '🎧 Helpdesk Corporativo', pct: 96, c: '#4d8fff' },
    { nm: '🖥️ Suporte a Hardware', pct: 92, c: '#ff8f3f' },
    { nm: '🔧 Manutenção Preventiva', pct: 88, c: '#10e8a0' },
    { nm: '🖨️ Impressoras & Periféricos', pct: 90, c: '#ffe066' },
    { nm: '📺 Monitores & TVs', pct: 94, c: '#00d4ff' },
    { nm: '💻 Notebooks & PCs', pct: 86, c: '#9d6fff' },
    { nm: '📧 Microsoft 365 / Office', pct: 84, c: '#ff5fa0' },
    { nm: '🌐 Infraestrutura de TI', pct: 78, c: '#10e8a0' },
    { nm: '📱 WhatsApp & Comunicação', pct: 72, c: '#4d8fff' },
    { nm: '🛠️ Gestão de Incidentes', pct: 91, c: '#ff8f3f' },
    { nm: '🔐 Controle de Acesso / Facial', pct: 80, c: '#00d4ff' },
    { nm: '🎬 Suporte a Eventos & Mídia', pct: 78, c: '#9d6fff' },
  ],
  TL: [
    { dt: 'Jul/2026', co: 'FIC CAPITAL', cc: '#00d4ff', ttl: 'Atualização Jun–Jul 2026', desc: '37 atividades registradas — relatório relatorio giovannne.pdf consolidado.' },
    { dt: '02–05/Jul', co: 'FIC CAPITAL', cc: '#4d8fff', ttl: 'Helpdesk e infra Jul/26', desc: 'Facial Augusto Mariano, filmagens ANIMA, podcast, monitores, impressoras e TVs.' },
    { dt: '03–09/Jul', co: 'FIC CAPITAL', cc: '#10e8a0', ttl: 'E-mail Advisor e treinamento', desc: 'Criação de e-mail Advisor, brigada de incêndio e validação de vagas.' },
    { dt: 'Mai/2026', co: 'FIC CAPITAL', cc: '#4d8fff', ttl: 'Início na FIC Capital', desc: 'Integração ao departamento de TI e início do suporte técnico.' },
    { dt: 'Mai/2025', co: 'FIC CAPITAL', cc: '#9d6fff', ttl: 'Apresentação Radar Benefits', desc: 'Demonstração corporativa do produto Radar Benefits para stakeholders.' },
    { dt: 'Jun/2025 — Sem. 1', co: 'FIC CAPITAL', cc: '#10e8a0', ttl: 'Atendimentos de alta prioridade', desc: 'Monitor Luca, impressora Samara Souza, monitor Caroline e validação de vagas.' },
    { dt: '12–13/Jun', co: 'FIC CAPITAL', cc: '#ff8f3f', ttl: 'Formatação e configuração', desc: 'Helpdesk Larry, formatação de máquinas e HelpDesk Jorge Salsa.' },
    { dt: '13–17/Jun', co: 'FIC CAPITAL', cc: '#00d4ff', ttl: 'Helpdesk de equipamentos', desc: 'Monitores, notebooks, TV, impressora, WhatsApp e Office 365.' },
    { dt: '20–26/Jun', co: 'FIC CAPITAL', cc: '#ffe066', ttl: 'Manutenções contínuas', desc: 'Troca de periférico, manutenção de vagas, e-mail licença compartilhada e navegador.' },
    { dt: 'Jun/2025', co: 'FIC CAPITAL', cc: '#10e8a0', ttl: 'Consolidação mensal', desc: '42 tarefas registradas — relatório mensal de performance concluído.' },
  ],
  ACH: [
    { icon: 'trophy', ttl: 'Volume Mensal', val: '42', accent: '#4d8fff', ds: 'Tarefas em Jun/25 — relatório mensal consolidado' },
    { icon: 'metric', ttl: 'Taxa de Conclusão', val: '100%', accent: '#10e8a0', ds: 'Todas as atividades documentadas como concluídas' },
    { icon: 'alert', ttl: 'Helpdesk', val: '28', accent: '#ff8f3f', ds: 'Chamados de suporte atendidos no período' },
    { icon: 'layers', ttl: 'Categorias', val: '5', accent: '#9d6fff', ds: 'Helpdesk, manutenção, infra, apresentações e outros' },
    { icon: 'org', ttl: 'Equipamentos', val: '5', accent: '#00d4ff', ds: 'Tipos de hardware mais atendidos no mês' },
    { icon: 'calendar', ttl: 'Jun–Jul 2026', val: '37', accent: '#00d4ff', ds: 'Atividades do relatório atualizado · 100% concluídas' },
    { icon: 'alert', ttl: 'Urgente', val: '1', accent: '#ff5a5a', ds: 'E-mail licença compartilhada Soft. Eng. e Arq.' },
  ],
  ANALYSIS: [
    {
      feat: true, wide: false, icon: 'exec', accent: '#4d8fff', ttl: 'Resumo Executivo',
      body: '<p>Giovane Oliveira atuou no <strong>Departamento de TI &amp; Helpdesk</strong> do Grupo FIC Capital no relatório mensal de <strong>Jun/2025</strong>. Registrou <strong>42 atividades</strong> com 100% de conclusão, com forte foco em helpdesk (28 chamados), manutenção preventiva/corretiva (7) e suporte a infraestrutura (4).</p>',
    },
    {
      feat: false, wide: false, icon: 'user', accent: '#00d4ff', ttl: 'Perfil Profissional',
      body: '<p>Profissional de suporte técnico com atuação em helpdesk corporativo, manutenção de equipamentos e atendimento a usuários. Integrado à FIC desde <strong>Mai/2026</strong>, com entregas consistentes em hardware, software e comunicação corporativa.</p>',
    },
    {
      feat: false, wide: false, icon: 'scope', accent: '#9d6fff', ttl: 'Principais Áreas',
      body: '<ul class="an-list"><li>Helpdesk geral e suporte a usuários</li><li>Manutenção preventiva e corretiva</li><li>Infraestrutura e configuração de equipamentos</li><li>Monitores, TVs, impressoras e notebooks</li><li>Microsoft 365 e licenças compartilhadas</li></ul>',
    },
    {
      feat: false, wide: false, icon: 'strength', accent: '#ffe066', ttl: 'Pontos Fortes',
      body: '<ul class="an-list"><li>100% das tarefas concluídas no período</li><li>Alto volume de helpdesk resolvido (28)</li><li>Cobertura ampla de equipamentos (monitores, impressoras, PCs)</li><li>Resposta a demandas prioritárias (41 itens)</li><li>Atuação contínua em manutenção de vagas e periféricos</li></ul>',
    },
    {
      feat: false, wide: false, icon: 'stack', accent: '#10e8a0', ttl: 'Tecnologias & Ferramentas',
      body: '<ul class="an-list"><li>Microsoft 365 / Office</li><li>WhatsApp corporativo</li><li>Hardware: monitores, TVs, notebooks, impressoras</li><li>Formatação e configuração de estações</li><li>Licenças de e-mail compartilhado</li></ul>',
    },
    {
      feat: true, wide: true, icon: 'impact', accent: '#ff8f3f', ttl: 'Impacto para a Organização',
      body: '<p>Garantiu a <strong>operacionalidade do parque de equipamentos</strong>, reduziu interrupções com manutenção preventiva e manteve o <strong>helpdesk responsivo</strong> para colaboradores da FIC Capital, com destaque para monitores/TVs (12 atendimentos) e impressoras (8).</p>',
    },
    {
      feat: true, wide: true, icon: 'exec', accent: '#00d4ff', ttl: 'Complemento — Jun–Jul 2026',
      body: '<p>Relatório atualizado (<em>relatorio giovannne.pdf</em>): <strong>37 atividades</strong> em Jun–Jul/2026, <strong>100% concluídas</strong>, 36 com prioridade e 1 urgente. Destaques: cadastro facial (Augusto Mariano), filmagens ANIMA, podcast Ficcionários, criação de e-mail Advisor, monitores (Luca/Caroline), impressoras, TVs, Office365, WhatsApp e manutenções preventivas.</p>',
    },
  ],
  TASKS: [
    { name: 'Integração ao departamento de TI — início FIC', cat: 'outros', mon: 'mai26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '01/05' },
    { name: 'Monitor – Luca', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '02/06' },
    { name: 'Impressora – Samara Souza', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '03/06' },
    { name: 'Monitor – Caroline', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '03/06' },
    { name: 'Validação de vagas', cat: 'outros', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '04/06' },
    { name: 'Apresentação produto Radar Benefits', cat: 'apresentacoes', mon: 'mai25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '23/05' },
    { name: 'Helpdesk – Larry', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '12/06' },
    { name: 'Formatação de máquina', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '13/06' },
    { name: 'HelpDesk Jorge Salsa', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '13/06' },
    { name: 'Manutenção Preventiva – Fábio', cat: 'manutencao', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '13/06' },
    { name: 'Manutenção Vaga – Estacionamento', cat: 'manutencao', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '13/06' },
    { name: 'E-mail – licença compartilhada', cat: 'infra', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '26/05' },
    { name: 'Troca de periférico', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '20/06' },
    { name: 'Manutenção de vagas', cat: 'manutencao', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '21/06' },
    { name: 'Problema no navegador', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '22/06' },
    { name: 'Suporte a monitores', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '14/06' },
    { name: 'Notebooks para agosto', cat: 'infra', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '15/06' },
    { name: 'Televisão — configuração', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '15/06' },
    { name: 'Impressora — manutenção', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '16/06' },
    { name: 'WhatsApp — suporte', cat: 'infra', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '16/06' },
    { name: 'Office 365 — configuração', cat: 'infra', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '17/06' },
    { name: 'Monitor / TV — chamado #1', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '05/06' },
    { name: 'Monitor / TV — chamado #2', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '06/06' },
    { name: 'Monitor / TV — chamado #3', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '07/06' },
    { name: 'Impressora — chamado #1', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '08/06' },
    { name: 'Impressora — chamado #2', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '09/06' },
    { name: 'Notebook / PC — suporte #1', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '10/06' },
    { name: 'Notebook / PC — suporte #2', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '11/06' },
    { name: 'Periféricos — troca e teste', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '18/06' },
    { name: 'Software / Office — instalação', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '19/06' },
    { name: 'Manutenção preventiva — estação #1', cat: 'manutencao', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '06/06' },
    { name: 'Manutenção preventiva — estação #2', cat: 'manutencao', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '10/06' },
    { name: 'Manutenção preventiva — estação #3', cat: 'manutencao', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '17/06' },
    { name: 'Helpdesk geral — demanda #1', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '01/06' },
    { name: 'Helpdesk geral — demanda #2', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '24/06' },
    { name: 'Helpdesk geral — demanda #3', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '25/06' },
    { name: 'Helpdesk geral — demanda #4', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '26/06' },
    { name: 'Helpdesk geral — demanda #5', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '27/06' },
    { name: 'Helpdesk geral — demanda #6', cat: 'helpdesk', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '28/06' },
    { name: 'Incidente urgente — resolução', cat: 'helpdesk', mon: 'jun25', pri: 'urgente', co: 'FIC CAPITAL', dt: '18/06' },
    { name: 'Outros — suporte complementar #1', cat: 'outros', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '23/06' },
    { name: 'Outros — suporte complementar #2', cat: 'outros', mon: 'jun25', pri: 'prioridade', co: 'FIC CAPITAL', dt: '24/06' },
    /* ── Jun–Jul 2026 · relatorio giovannne.pdf ── */
    { name: 'Pode Subir – Cadastrar Facial – Augusto Mariano', cat: 'infra', mon: 'jul26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '02/07' },
    { name: 'Filmagens – Anima', cat: 'outros', mon: 'jul26', pri: 'prioridade', co: 'ANIMA', dt: '02/07' },
    { name: 'Podcast – Ficcionarios 03/06 – Wagner Mota', cat: 'apresentacoes', mon: 'jul26', pri: 'prioridade', co: 'FICCIONARIOS', dt: '02/07' },
    { name: 'Criação de email para Advisor', cat: 'infra', mon: 'jul26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '03/07' },
    { name: 'Treinamento – Brigada de Incêndio', cat: 'outros', mon: 'jul26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '09/07' },
    { name: 'Monitor não liga – Luca', cat: 'helpdesk', mon: 'jul26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '05/07' },
    { name: 'Impressora não funciona', cat: 'helpdesk', mon: 'jul26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '05/07' },
    { name: 'Impressora – Samara Souza', cat: 'helpdesk', mon: 'jul26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '05/07' },
    { name: 'Verificar os cabos da Televisão – Corredor', cat: 'helpdesk', mon: 'jul26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '05/07' },
    { name: 'Monitor não está ligando – Caroline', cat: 'helpdesk', mon: 'jul26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '05/07' },
    { name: 'Validação de vagas estacionamento – Francisco', cat: 'outros', mon: 'jul26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '05/07' },
    { name: 'Helpdesk – Troca de Monitor', cat: 'helpdesk', mon: 'jul26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '05/07' },
    { name: 'Organograma Corporativo – Office365', cat: 'infra', mon: 'jul26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '05/07' },
    { name: 'Helpdesk – Jorge Salsa', cat: 'helpdesk', mon: 'jul26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '05/07' },
    { name: 'Helpdesk – Preparar notebook', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '26/06' },
    { name: 'Helpdesk – Documento', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '25/06' },
    { name: 'Preparar Sala de Reunião – Luca', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '25/06' },
    { name: 'Manutenção de vagas – Estacionamento', cat: 'manutencao', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '25/06' },
    { name: 'Helpdesk – Documentos', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '24/06' },
    { name: 'Helpdesk – Televisão', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '24/06' },
    { name: 'Email para licença compartilhada Soft. Eng. e Arq.', cat: 'infra', mon: 'mai26', pri: 'urgente', co: 'FIC CAPITAL', dt: '26/05' },
    { name: 'Helpdesk – Troca de periférico', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '20/06' },
    { name: 'Helpdesk – Computador com problema', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '20/06' },
    { name: 'Helpdesk – Problema no Navegador', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '18/06' },
    { name: 'Helpdesk – Notebook para Agosto', cat: 'infra', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '17/06' },
    { name: 'Helpdesk – Monitores', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '17/06' },
    { name: 'Helpdesk – Office365', cat: 'infra', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '17/06' },
    { name: 'Televisão – Imagens', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '14/06' },
    { name: 'Helpdesk – Whatsapp', cat: 'infra', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '14/06' },
    { name: 'Helpdesk – Documento', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '14/06' },
    { name: 'Helpdesk – Impressora', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '14/06' },
    { name: 'Manutenção Preventiva – Fábio', cat: 'manutencao', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '13/06' },
    { name: 'Manutenção Vaga – Estacionamento', cat: 'manutencao', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '13/06' },
    { name: 'Helpdesk – Larry', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '13/06' },
    { name: 'Helpdesk – Formatação de Máquina', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '12/06' },
    { name: 'Helpdesk – Formatação de máquina', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '12/06' },
    { name: 'HelpDesk – Jorge Salsa', cat: 'helpdesk', mon: 'jun26', pri: 'prioridade', co: 'FIC CAPITAL', dt: '12/06' },
  ],
};
