/* Dados — Marina Rodrigues · Relatorio_Claude.pdf · RSA Dashboard 1S2026 · Jan–Jun 2026 */
window.MARINA_REPORT = {
  CATMAP: {
    planejamento: { color: '#4d8fff', label: 'Planejamento' },
    execucao:     { color: '#00d4ff', label: 'Execução' },
    controle:     { color: '#ffb020', label: 'Controle' },
    manutencao:   { color: '#10e8a0', label: 'Manutenção' },
    equipamentos: { color: '#ff8f3f', label: 'Equipamentos' },
    facilities:   { color: '#9d6fff', label: 'Facilities' },
  },
  KPIS: [
    { ic: '📋', label: 'Demandas no Semestre', val: '23', sub: 'Infraestrutura · Jan–Jun 2026', color: '#4d8fff' },
    { ic: '✅', label: 'Concluídas', val: '23', sub: '100% de execução', color: '#10e8a0' },
    { ic: '🔧', label: 'Manutenção Preventiva', val: '9', sub: 'PCs, notebooks e geral', color: '#ffb020' },
    { ic: '💻', label: 'Estações & Equipamentos', val: '8', sub: 'Mudanças, TVs e formatações', color: '#ff8f3f' },
    { ic: '🏗️', label: 'Memorial ANIMA', val: '16', sub: 'Etapas técnicas do memorial', color: '#9d6fff' },
    { ic: '⚡', label: 'Urgentes / Emergentes', val: '4', sub: 'Prioridade máxima', color: '#ff5a5a' },
    { ic: '🏢', label: 'Empresas Atendidas', val: '3', sub: 'FIC · ANIMA · parceiros', color: '#00d4ff' },
    { ic: '📊', label: 'RSA Dashboard', val: '1S26', sub: 'Planejamento · Execução · Controle', color: '#ffe066' },
  ],
  MON_L: ['Jan/26', 'Fev/26', 'Mar/26', 'Abr/26', 'Mai/26', 'Jun/26'],
  MON_D: [0, 1, 10, 8, 4, 0],
  CAT_L: ['Manutenção', 'Equipamentos', 'Facilities', 'Controle', 'Execução', 'Planejamento'],
  CAT_D: [9, 8, 2, 3, 4, 1],
  CAT_C: ['#10e8a0', '#ff8f3f', '#9d6fff', '#ffb020', '#00d4ff', '#4d8fff'],
  TOP_L: ['Manutenção preventiva', 'Atualização preventiva', 'Manutenção notebook', 'Mudança estação/PC', 'TVs e monitores', 'Obras ANIMA', 'Formatação', 'VR / periféricos'],
  TOP_D: [5, 5, 4, 4, 2, 2, 1, 1],
  SKILLS: [
    { nm: '📋 Gestão de Demandas', pct: 92, c: '#4d8fff' },
    { nm: '🔧 Manutenção Preventiva', pct: 94, c: '#10e8a0' },
    { nm: '💻 Estações de Trabalho', pct: 88, c: '#ff8f3f' },
    { nm: '📺 TVs & Monitores', pct: 86, c: '#00d4ff' },
    { nm: '🏗️ Facilities Corporativos', pct: 82, c: '#9d6fff' },
    { nm: '⚙️ Controle & Priorização', pct: 90, c: '#ffb020' },
    { nm: '🖥️ Notebooks & Mini PCs', pct: 87, c: '#4d8fff' },
    { nm: '📐 Planejamento de Infra', pct: 85, c: '#10e8a0' },
    { nm: '🤝 Atendimento Multiempresa', pct: 88, c: '#ffe066' },
    { nm: '📊 RSA Dashboard 2026', pct: 91, c: '#00d4ff' },
  ],
  TL: [
    { dt: 'Jan/2026', co: 'FIC GROUP', cc: '#4d8fff', ttl: 'RSA 1S2026 — início do ciclo', desc: 'Planejamento do dashboard de tarefas · gestão de demandas de infraestrutura.' },
    { dt: 'Fev/2026', co: 'FIC', cc: '#ff5a5a', ttl: 'Manutenção notebook urgente', desc: 'Atendimento prioritário de solicitação de manutenção corporativa.' },
    { dt: 'Mar/2026', co: 'FIC', cc: '#10e8a0', ttl: 'Pico de preventivas', desc: 'Série de atualizações preventivas (#1–#5), manutenção geral e preventiva de PCs.' },
    { dt: 'Abr/2026', co: 'FIC', cc: '#ff8f3f', ttl: 'Estações e notebooks', desc: 'Mudanças de PC/tela, manutenção de notebooks, formatação mini PC e estação Samara.' },
    { dt: 'Mai/2026', co: 'ANIMA', cc: '#9d6fff', ttl: 'Memorial banheiros ANIMA', desc: 'Elaboração do memorial descritivo da reforma — Wellness Club (16 capítulos técnicos).' },
    { dt: 'Jun/2026', co: 'FIC GROUP', cc: '#00d4ff', ttl: 'Relatório semestral', desc: 'Consolidação RSA · 22 demandas de infraestrutura no 1º semestre 2026.' },
  ],
  ACH: [
    { icon: 'trophy', ttl: 'Taxa de Conclusão', val: '100%', accent: '#10e8a0', ds: '23 de 23 demandas finalizadas' },
    { icon: 'metric', ttl: 'Preventivas', val: '9', accent: '#ffb020', ds: 'Manutenções e atualizações programadas' },
    { icon: 'layers', ttl: 'Categorias', val: '6', accent: '#4d8fff', ds: 'Planejamento, execução, controle e operações' },
    { icon: 'org', ttl: 'Multiempresa', val: '3', accent: '#00d4ff', ds: 'FIC · ANIMA · atendimentos corporativos' },
    { icon: 'alert', ttl: 'Prioritárias', val: '4', accent: '#ff5a5a', ds: 'Urgentes e emergentes resolvidas' },
    { icon: 'layers', ttl: 'Memorial ANIMA', val: '16', accent: '#9d6fff', ds: 'Capítulos do memorial descritivo de banheiros' },
  ],
  ANALYSIS: [
    {
      feat: true, wide: false, icon: 'exec', accent: '#ffb020', ttl: 'Resumo Executivo',
      body: '<p><strong>Marina Rodrigues</strong> atua em <strong>Infraestrutura</strong> no FIC Capital Group no <strong>RSA Dashboard 1S2026</strong>. Destaque para o <strong>Memorial Descritivo — Reforma de Banheiros ANIMA</strong> (<em>MEMORIAL DESCRITIVO BANHEIROS ANIMA.docx</em>), com 16 etapas técnicas (hidráulica, elétrica, revestimentos, acessibilidade NBR 9050 e entrega). No semestre: <strong>22 demandas</strong> de infraestrutura corporativa.</p>',
    },
    {
      feat: false, wide: false, icon: 'user', accent: '#00d4ff', ttl: 'Perfil Profissional',
      body: '<p>Profissional de infraestrutura corporativa com atuação em manutenção de ativos, suporte a ambientes físicos e digitais, priorização de chamados e acompanhamento de entregas no ecossistema FIC Capital Group.</p>',
    },
    {
      feat: false, wide: false, icon: 'scope', accent: '#4d8fff', ttl: 'Principais Áreas',
      body: '<ul class="an-list"><li>Planejamento e controle de demandas (RSA)</li><li>Manutenção preventiva e corretiva</li><li>Estações de trabalho, PCs e notebooks</li><li>TVs, monitores e periféricos</li><li>Facilities e obras (ANIMA)</li><li>Execução multiempresa</li></ul>',
    },
    {
      feat: false, wide: false, icon: 'strength', accent: '#10e8a0', ttl: 'Pontos Fortes',
      body: '<ul class="an-list"><li>100% de conclusão no semestre documentado</li><li>Volume concentrado de preventivas em março</li><li>Resposta a demandas urgentes e emergentes</li><li>Cobertura FIC + projetos ANIMA</li><li>Padronização via RSA Dashboard 2026</li></ul>',
    },
    {
      feat: false, wide: false, icon: 'stack', accent: '#ff8f3f', ttl: 'Entregas Recorrentes',
      body: '<ul class="an-list"><li>Atualizações preventivas em lote</li><li>Manutenção de notebooks e PCs corporativos</li><li>Mudança de estações e telas</li><li>Renomeação e gestão de TVs</li><li>Obras e revestimentos (facilities)</li></ul>',
    },
    {
      feat: true, wide: true, icon: 'impact', accent: '#9d6fff', ttl: 'Impacto para a Organização',
      body: '<p>Garantiu a <strong>continuidade operacional da infraestrutura física e de TI</strong> do grupo, com manutenções preventivas que reduzem paradas, organização de ativos (TVs, notebooks, mini PCs) e execução de melhorias em facilities, alinhadas ao modelo <strong>Planejamento · Execução · Controle</strong> do RSA 1S2026.</p>',
    },
  ],
  TASKS: [
    { name: 'Solicitação manutenção notebook', cat: 'manutencao', mon: 'fev26', pri: 'urgente', co: 'FIC', dt: '22/02' },
    { name: 'Manutenção preventiva', cat: 'manutencao', mon: 'mar26', pri: 'prioridade', co: 'FIC', dt: '14/03' },
    { name: 'Adquirido VR pessoal', cat: 'equipamentos', mon: 'mar26', pri: 'prioridade', co: 'FIC', dt: '13/03' },
    { name: 'Atualização preventiva #1', cat: 'manutencao', mon: 'mar26', pri: 'prioridade', co: 'FIC', dt: '13/03' },
    { name: 'Atualização preventiva #2', cat: 'manutencao', mon: 'mar26', pri: 'prioridade', co: 'FIC', dt: '13/03' },
    { name: 'Atualização preventiva #3', cat: 'manutencao', mon: 'mar26', pri: 'prioridade', co: 'FIC', dt: '13/03' },
    { name: 'Atualização preventiva #4', cat: 'manutencao', mon: 'mar26', pri: 'prioridade', co: 'FIC', dt: '13/03' },
    { name: 'Atualização preventiva #5', cat: 'manutencao', mon: 'mar26', pri: 'prioridade', co: 'FIC', dt: '13/03' },
    { name: 'Manutenção preventiva PC', cat: 'manutencao', mon: 'mar26', pri: 'prioridade', co: 'FIC', dt: '07/03' },
    { name: 'Manutenção preventiva geral', cat: 'manutencao', mon: 'mar26', pri: 'prioridade', co: 'FIC', dt: '14/03' },
    { name: 'Mudança de tela PC', cat: 'equipamentos', mon: 'abr26', pri: 'prioridade', co: 'FIC', dt: '22/04' },
    { name: 'Mudança de PC', cat: 'equipamentos', mon: 'abr26', pri: 'emergente', co: 'FIC', dt: '07/04' },
    { name: 'Mudar estação de trabalho Samara', cat: 'equipamentos', mon: 'abr26', pri: 'urgente', co: 'FIC', dt: '09/04' },
    { name: 'Manutenção PC corporativo', cat: 'manutencao', mon: 'abr26', pri: 'prioridade', co: 'DECPCINATOS', dt: '06/04' },
    { name: 'Formatação mini PC', cat: 'execucao', mon: 'abr26', pri: 'prioridade', co: 'FIC', dt: '19/04' },
    { name: 'Manutenção notebook #1', cat: 'manutencao', mon: 'abr26', pri: 'prioridade', co: 'FIC', dt: '18/04' },
    { name: 'Manutenção notebook #2', cat: 'manutencao', mon: 'abr26', pri: 'prioridade', co: 'FIC', dt: '18/04' },
    { name: 'Manutenção notebook #3', cat: 'manutencao', mon: 'abr26', pri: 'prioridade', co: 'FIC', dt: '19/04' },
    { name: 'Manutenção geral', cat: 'controle', mon: 'mai26', pri: 'prioridade', co: 'FIC', dt: '08/05' },
    { name: 'Renomear todas as TVs', cat: 'equipamentos', mon: 'mai26', pri: 'urgente', co: 'FIC', dt: '31/05' },
    { name: 'Memorial descritivo — banheiros ANIMA', cat: 'facilities', mon: 'mai26', pri: 'prioridade', co: 'ANIMA', dt: '19/05' },
    { name: 'Desenvolvimento banheiros ANIMA', cat: 'facilities', mon: 'mai26', pri: 'prioridade', co: 'ANIMA', dt: '19/05' },
    { name: 'Revestimento Tijolinhos', cat: 'facilities', mon: 'mai26', pri: 'prioridade', co: 'ANIMA', dt: '19/05' },
  ],
};
