/* Dados do relatório Samara Gomes — fonte: samara relatorio.docx (Abr–Jul 2026) */
window.SAMARA_REPORT = {
  CATMAP: {
    propostas:    { color: '#c4a8dc', label: 'Propostas RCI' },
    reunioes:     { color: '#d4a5b8', label: 'Reuniões' },
    agendamentos: { color: '#9ec9b0', label: 'Agendamentos' },
    documentos:   { color: '#e8d8b0', label: 'Documentação' },
    eventos:      { color: '#e8c0a8', label: 'Eventos' },
    operacional:  { color: '#e8b4cc', label: 'Operacional' },
    comercial:    { color: '#f0a8c4', label: 'Comercial' },
  },
  KPIS: [
    { ic: '✅', label: 'Total de Atividades', val: '48', sub: 'Executadas no período', color: '#d4a5b8' },
    { ic: '📈', label: 'Taxa de Conclusão', val: '94%', sub: '45 de 48 concluídas', color: '#9ec9b0' },
    { ic: '📄', label: 'Propostas RCI', val: '17', sub: 'Geradas em 3 meses', color: '#c4a8dc' },
    { ic: '🤝', label: 'Reuniões & Eventos', val: '11', sub: 'Reuniões estratégicas', color: '#e8c0a8' },
    { ic: '📅', label: 'Agendamentos', val: '7', sub: 'Executivos e G4', color: '#e8b4cc' },
    { ic: '📊', label: 'Planilhas Criadas', val: '6', sub: 'Advisor, EcoRedux, leads', color: '#e8d8b0' },
    { ic: '🏢', label: 'Clientes Abordados', val: '15+', sub: 'Empresas no pipeline', color: '#f0a8c4' },
    { ic: '🗓️', label: 'Agendas Gerenciadas', val: '3', sub: 'Fábio, Luca, Giovanna', color: '#9ec9b0' },
  ],
  MON_L: ['Abr/26', 'Mai/26', 'Jun/26', 'Jul/26'],
  MON_D: [2, 14, 26, 6],
  CAT_L: ['Propostas RCI', 'Reuniões', 'Agendamentos', 'Documentação', 'Eventos', 'Operacional'],
  CAT_D: [17, 11, 7, 6, 4, 3],
  CAT_C: ['#c4a8dc', '#d4a5b8', '#9ec9b0', '#e8d8b0', '#e8c0a8', '#e8b4cc'],
  TOP_L: ['Propostas RCI', 'Reuniões estratégicas', 'Agenda executiva', 'Planilhas de controle', 'Workshops / eventos'],
  TOP_D: [17, 11, 7, 6, 4],
  SKILLS: [
    { nm: '📞 BDR & Prospecção', pct: 92, c: '#c4a8dc' },
    { nm: '📅 Gestão de Agendas', pct: 96, c: '#9ec9b0' },
    { nm: '📄 Propostas Comerciais RCI', pct: 90, c: '#d4a5b8' },
    { nm: '🤝 Reuniões & Eventos', pct: 94, c: '#e8c0a8' },
    { nm: '📊 Planilhas & Controles', pct: 88, c: '#e8d8b0' },
    { nm: '💬 Comunicação Corporativa', pct: 91, c: '#e8b4cc' },
    { nm: '🎯 Tráfego Pago & Leads', pct: 85, c: '#f0a8c4' },
    { nm: '🏢 Multi-unidades (FIC Group)', pct: 89, c: '#9ec9b0' },
    { nm: '📋 Documentação Operacional', pct: 87, c: '#d4a5b8' },
    { nm: '⚡ Organização & Follow-up', pct: 93, c: '#e8c0a8' },
  ],
  TL: [
    { dt: 'Abr/2026', co: 'LEGALCERT', cc: '#c4a8dc', ttl: 'Ingresso como BDR', desc: 'Início em 07/04/2026 — Business Development Representative, reporte à Head Comercial.' },
    { dt: 'Mai/2026', co: 'LEGALCERT', cc: '#e8d8b0', ttl: 'Planilhas Advisor & Tráfego Pago', desc: 'Planilha de Advisor, controle de leads e atividades de tráfego pago.' },
    { dt: 'Jun/2026', co: 'RWB', cc: '#d4a5b8', ttl: 'Pico de propostas e reuniões', desc: '17 propostas RCI, reuniões com Richard Rasmussen, Ricardo Magalhães e Hipica.' },
    { dt: 'Jun/2026', co: 'FIC', cc: '#9ec9b0', ttl: 'Agendas executivas', desc: 'Organização da agenda Fábio (CEO), Luca e Giovanna Head — 3 agendas simultâneas.' },
    { dt: 'Jul/2026', co: 'LEGALCERT', cc: '#e8c0a8', ttl: 'Workshop & treinamentos', desc: 'Workshop Legalcert, treinamento Advisor com Giovanna e podcast Caio Soares (IA).' },
    { dt: 'Jul/2026', co: 'LIV / SINATRA', cc: '#e8b4cc', ttl: 'Expansão multi-unidades', desc: 'Reuniões com Daniel Miglorancia (LIV) e Thiago (SINATRA).' },
    { dt: 'Jul/2026', co: 'FIC GROUP', cc: '#9ec9b0', ttl: 'Consolidação do período', desc: '48 atividades — 93,75% de conclusão no relatório Abr–Jul 2026.' },
  ],
  ACH: [
    { icon: 'trophy', ttl: 'Propostas RCI', val: '17', accent: '#c4a8dc', ds: 'Propostas comerciais geradas em 3 meses' },
    { icon: 'metric', ttl: 'Taxa de Conclusão', val: '94%', accent: '#9ec9b0', ds: '45 atividades concluídas de 48 registradas' },
    { icon: 'calendar', ttl: 'Agendas CEO', val: '3', accent: '#e8b4cc', ds: 'Fábio Tenório, Luca e Giovanna Head' },
    { icon: 'org', ttl: 'Clientes', val: '15+', accent: '#e8c0a8', ds: 'Empresas e clientes abordados no período' },
    { icon: 'layers', ttl: 'Unidades', val: '6', accent: '#d4a5b8', ds: 'Legalcert, RWB, FIC, LIV, SINATRA, G4' },
    { icon: 'alert', ttl: 'Reuniões', val: '11', accent: '#e8d8b0', ds: 'Reuniões e eventos estratégicos agendados' },
  ],
  ANALYSIS: [
    {
      feat: true, wide: false, icon: 'exec', accent: '#d4a5b8', ttl: 'Resumo Executivo',
      body: '<p>Samara Gomes David atua como <strong>BDR (Business Development Representative)</strong> desde <strong>07/04/2026</strong>, com reporte à Giovanna Head (Head Comercial). No período <strong>07/04 – 01/06/2026</strong>, executou <strong>48 atividades</strong> com <strong>93,75% de conclusão</strong>, incluindo 17 propostas RCI, 11 reuniões estratégicas e gestão de 3 agendas executivas.</p>',
    },
    {
      feat: false, wide: false, icon: 'user', accent: '#e8b4cc', ttl: 'Perfil Profissional',
      body: '<p>Profissional de desenvolvimento comercial e suporte operacional, com foco em prospecção, agendamentos executivos, propostas RCI e coordenação entre unidades do grupo FIC (Legalcert, RWB, FIC, LIV, SINATRA, G4).</p>',
    },
    {
      feat: false, wide: false, icon: 'scope', accent: '#c4a8dc', ttl: 'Principais Áreas',
      body: '<ul class="an-list"><li>Gerenciamento de agendas executivas</li><li>Desenvolvimento comercial e prospecção</li><li>Propostas RCI e pipeline comercial</li><li>Comunicação e coordenação entre departamentos</li><li>Planilhas e documentação operacional</li><li>Eventos, workshops e tráfego pago</li></ul>',
    },
    {
      feat: false, wide: false, icon: 'strength', accent: '#e8d8b0', ttl: 'Pontos Fortes',
      body: '<ul class="an-list"><li>Alta taxa de conclusão (93,75%)</li><li>Volume consistente de propostas RCI (17)</li><li>Gestão simultânea de múltiplas agendas de alto nível</li><li>Organização em ambiente multiempresarial</li><li>Aprendizado rápido em função BDR</li></ul>',
    },
    {
      feat: false, wide: false, icon: 'stack', accent: '#9ec9b0', ttl: 'Ferramentas & Entregas',
      body: '<ul class="an-list"><li>Planilhas Advisor, EcoRedux e leads (tráfego pago)</li><li>Propostas comerciais RCI</li><li>Checklists e documentação de suporte</li><li>Coordenação de workshops e eventos G4</li><li>Comunicação com prospects e parceiros</li></ul>',
    },
    {
      feat: true, wide: true, icon: 'impact', accent: '#e8c0a8', ttl: 'Impacto para a Organização',
      body: '<p>Atua como <strong>elo entre agendas executivas, comercial e operações</strong>, estruturando oportunidades via propostas RCI, reuniões estratégicas e eventos corporativos. O desempenho inicial posiciona-a como recurso estratégico para expansão comercial da FIC e empresas associadas.</p>',
    },
  ],
  TASKS: [
    { name: 'Ingresso BDR — início Legalcert', cat: 'comercial', mon: 'abr26', pri: 'prioridade', co: 'LEGALCERT', dt: '07/04' },
    { name: 'TRÁFEGO PAGO', cat: 'comercial', mon: 'mai26', pri: 'prioridade', co: 'LEGALCERT', dt: '06/05' },
    { name: 'TRÁFEGO PAGO | Planilha de controle de leads', cat: 'documentos', mon: 'mai26', pri: 'prioridade', co: 'LEGALCERT', dt: '07/05' },
    { name: 'PLANILHA DE ADVISOR', cat: 'documentos', mon: 'mai26', pri: 'prioridade', co: 'LEGALCERT', dt: '07/05' },
    { name: 'AGENDAMENTOS FÁBIO | Certificados digitais', cat: 'agendamentos', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '11/06' },
    { name: 'AGENDAMENTO | FÁBIO | M. COMPANY', cat: 'agendamentos', mon: 'jun26', pri: 'standby', co: 'LEGALCERT', dt: '11/06' },
    { name: 'AGENDAMENTOS | FÁBIO | G4 CLUB', cat: 'agendamentos', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '11/06' },
    { name: 'PLANILHA ECOREDUX', cat: 'documentos', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '11/06' },
    { name: 'REUNIÃO | BIOFEED | FÁBIO', cat: 'reunioes', mon: 'jun26', pri: 'prioridade', co: 'RWB', dt: '11/06' },
    { name: 'MENSAGENS WORKSHOP', cat: 'eventos', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '17/06' },
    { name: 'PLANO DE REATIVAÇÃO | Planilha EcoRedux', cat: 'documentos', mon: 'jun26', pri: 'andamento', co: 'LEGALCERT', dt: '19/06' },
    { name: 'PROPOSTA RCI | DCELT', cat: 'propostas', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'PROPOSTA RCI | MOINHO XANXERE', cat: 'propostas', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'PROPOSTA RCI | Cooperativa Regional', cat: 'propostas', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'PROPOSTA RCI | META GALVANIZAÇÃO', cat: 'propostas', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'PROPOSTA RCI | ONDULNORTE', cat: 'propostas', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'PROPOSTA RCI | Celesc Distribuição SA', cat: 'propostas', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'PROPOSTA RCI | Cooperativa Extremo Oeste', cat: 'propostas', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'PROPOSTA RCI | Cooperativa do Extremo', cat: 'propostas', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'REUNIÃO | MineTOO aviações', cat: 'reunioes', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'REUNIÃO | Vice-presidente | Hipica Santo Amaro', cat: 'reunioes', mon: 'jun26', pri: 'prioridade', co: 'RWB', dt: '28/06' },
    { name: 'ENVIO DE CHECKLIST | Thiago Brandão', cat: 'documentos', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'ENVIO DE CHECKLIST | Empresa ARITA', cat: 'documentos', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'REUNIÃO COM RODRIGO ECOREDUX', cat: 'reunioes', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'EDUARDO GESTOR DE CONTAS DA G4', cat: 'operacional', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'ORGANIZAÇÃO AGENDA FÁBIO', cat: 'agendamentos', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'ALMOÇO | RICHARD RASMUSSEN', cat: 'reunioes', mon: 'jul26', pri: 'prioridade', co: 'RWB', dt: '01/07' },
    { name: 'REUNIÃO | COMUNICAÇÃO', cat: 'reunioes', mon: 'jul26', pri: 'prioridade', co: 'LEGALCERT', dt: '01/07' },
    { name: 'WORKSHOP | LEGALCERT', cat: 'eventos', mon: 'jul26', pri: 'prioridade', co: 'LEGALCERT', dt: '01/07' },
    { name: 'TREINAMENTO COM GIOVANNA | ADVISOR', cat: 'eventos', mon: 'jul26', pri: 'prioridade', co: 'LEGALCERT', dt: '01/07' },
    { name: 'REUNIÃO COM RICARDO MAGALHÃES | RWB', cat: 'reunioes', mon: 'jul26', pri: 'prioridade', co: 'RWB', dt: '01/07' },
    { name: 'AGENDAMENTO G4 | NOITE DO POKER', cat: 'eventos', mon: 'jul26', pri: 'prioridade', co: 'FIC', dt: '01/07' },
    { name: 'REUNIÃO COM RICHARD RASMUSSEN', cat: 'reunioes', mon: 'jul26', pri: 'prioridade', co: 'RWB', dt: '01/07' },
    { name: 'EDUARDO FIGUEREDO | G4', cat: 'operacional', mon: 'jul26', pri: 'prioridade', co: 'LEGALCERT', dt: '01/07' },
    { name: 'PODCAST CAIO SOARES | IA', cat: 'eventos', mon: 'jul26', pri: 'prioridade', co: 'LEGALCERT', dt: '01/07' },
    { name: 'REUNIÃO COM DANIEL MIGLORANCIA | LIV', cat: 'reunioes', mon: 'jul26', pri: 'prioridade', co: 'LIV', dt: '01/07' },
    { name: 'REUNIÃO COM THIAGO | SINATRA', cat: 'reunioes', mon: 'jul26', pri: 'prioridade', co: 'SINATRA', dt: '01/07' },
    { name: 'PROPOSTA RCI | MOINHO XANXERE #2', cat: 'propostas', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'PROPOSTA RCI | META GALVANIZAÇÃO #2', cat: 'propostas', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'PROPOSTA RCI | Cooperativa Regional Comercialização', cat: 'propostas', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'PROPOSTA RCI | Cooperativa Regional #3', cat: 'propostas', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '28/06' },
    { name: 'Sincronização agendas executivas', cat: 'agendamentos', mon: 'jun26', pri: 'prioridade', co: 'FIC', dt: '25/06' },
    { name: 'Follow-up tráfego pago', cat: 'comercial', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '24/06' },
    { name: 'Coordenação workshop Legalcert', cat: 'eventos', mon: 'jul26', pri: 'prioridade', co: 'LEGALCERT', dt: '01/07' },
    { name: 'Suporte reunião comunicação interna', cat: 'operacional', mon: 'jul26', pri: 'prioridade', co: 'LEGALCERT', dt: '01/07' },
    { name: 'Planejamento leads EcoRedux', cat: 'comercial', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '20/06' },
    { name: 'Agenda Luca — sincronização', cat: 'agendamentos', mon: 'jun26', pri: 'prioridade', co: 'RWB', dt: '26/06' },
    { name: 'Agenda Giovanna Head — sincronização', cat: 'agendamentos', mon: 'jun26', pri: 'prioridade', co: 'LEGALCERT', dt: '26/06' },
  ],
};
